### ISSUE TITLE
SIP not working with eJabberd and LDAP

### ISSUE THREAD

**Issue by arodier** [progmaticltd/homebox#250]
The SIP module for eJabberd apparently does not support LDAP.

More information in the links below:
- https://github.com/processone/ejabberd/issues/1419
- https://www.ejabberd.im/node/24717/index.html

One possible solution: external authentication with a script, and caching credentials:
- https://www.ejabberd.im/extauth/
- https://www.ejabberd.im/check_pass_ldap_perl/index.html

Maybe second option: common caching option? 
- https://docs.ejabberd.im/admin/configuration/#caching
- May not be supported with the version in Stretch.
- Not sure this option is intended for this.

**Comment by arodier** [comment]
The answer from eJabberd developers is they will not implement it.
Other options are possible, like kamailio or mumble.

**Comment by fredericmoulins** [comment]
From what I understand the concern for eJabberd developers, as well as the requester in processone/ejabberd#1419, is to store passwords either in cleartext (or with a weak hash).

For example, Kamalio seems to store the passwords in cleartext or in HA1 format ((MD5-)hash of username, realm, password), so the issue is the same.
https://www.kamailio.org/wiki/tutorials/mini-howto-admin/ldap-user-auth#ldap_tree

After a [bit of](https://en.wikipedia.org/wiki/Digest_access_authentication) pedagogic [reading](https://tools.ietf.org/html/rfc3261#section-22), it seems that the updated version of the Digest access authentication in [rfc7616](https://tools.ietf.org/html/rfc7616#section-3.2) includes SHA-2 hashes, but support for these in SIP is still [in draft](https://datatracker.ietf.org/doc/draft-ietf-sipcore-digest-scheme/), so I would guess the support in clients is lacking today. (By the way, [other authentication methods](https://datatracker.ietf.org/doc/draft-ietf-sipcore-sip-token-authnz/) are also being drafted.) The rfc7616 also have an extensive Security Considerations section. 

Anyway, it would be weird to have a user's salted SHA512 hashed password in the openldap database stored alongside the same password hashed in a weaker way.

Of course, those comments only consider the hashes, password storage and does not take into account any larger threat model, but situations such as this led service providers to implement app-specific passwords if there was no better authentication scheme available (eg Google with IMAP).

**Comment by fredericmoulins** [comment]
> Other options are possible, like kamailio or mumble.

Also related I think : Jitsi.

**Comment by arodier** [comment]
Yes, I understand all these points. I think mumble has an LDAP authentication option too, and since I need to add some voice function to the box, I will investigate this.
